"""Initial migration

Revision ID: 7365243d621f
Revises: 
Create Date: 2024-12-23 16:29:46.429827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7365243d621f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_mappings',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('bsky_uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_mappings')
    # ### end Alembic commands ###
