"""Added bsky_uri column to link_mappings table

Revision ID: a1167f7733e7
Revises: 84124552e8a8
Create Date: 2024-12-23 07:56:07.601263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1167f7733e7'
down_revision: Union[str, None] = '84124552e8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_mappings', sa.Column('bsky_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_mappings', 'bsky_uri')
    # ### end Alembic commands ###
